//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int AnsId { get; set; }
        public string Responsetype { get; set; }
        public string response { get; set; }
        public int QuestionId { get; set; }
        public int FeedbackID { get; set; }
    }
}
