//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppliedFor
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int JobID { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Student Student { get; set; }
    }
}
