//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CafeteriaStaff
    {
        public int StaffID { get; set; }
        public string Username { get; set; }
        public string SPassword { get; set; }
        public string SRole { get; set; }
    }
}
