//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateTestDetail
    {
        public int DetailsID { get; set; }
        public int CandidateID { get; set; }
        public int AssignedTestID { get; set; }
        public string TestScore { get; set; }
    }
}
