//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateEmployee
    {
        public int ECandidateID { get; set; }
        public string EName { get; set; }
        public string EAddress { get; set; }
        public string MobileNumber { get; set; }
        public string EducationLevel { get; set; }
        public int ExperienceYears { get; set; }
        public string CVpath { get; set; }
        public string Coverletterpath { get; set; }
        public string EPassword { get; set; }
        public string Email { get; set; }
    }
}
