//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClearanceRequest
    {
        public int RequestID { get; set; }
        public string ParentName1 { get; set; }
        public string ParentCNIC1 { get; set; }
        public string ParentName2 { get; set; }
        public string ParentCNIC2 { get; set; }
        public string SemesterGraduation { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int StudentID { get; set; }
        public string Status { get; set; }
    }
}
