//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseOffered
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseOffered()
        {
            this.CourseFaculties = new HashSet<CourseFaculty>();
            this.CourseFaculties1 = new HashSet<CourseFaculty>();
        }
    
        public int CourseOfferedID { get; set; }
        public int CreditHrs { get; set; }
        public int CourseNSections { get; set; }
        public int MaxStdPerSection { get; set; }
        public int BatchID { get; set; }
        public int SemesterID { get; set; }
        public int CourseID { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Batch Batch1 { get; set; }
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseFaculty> CourseFaculties { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseFaculty> CourseFaculties1 { get; set; }
        public virtual Semester Semester { get; set; }
    }
}
