//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseEnrollment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseEnrollment()
        {
            this.Attendances = new HashSet<Attendance>();
            this.StudentAssignments = new HashSet<StudentAssignment>();
        }
    
        public int EnrollmentID { get; set; }
        public string CourseStatus { get; set; }
        public string IsFeedBackSubmit { get; set; }
        public int FSID { get; set; }
        public int StudentID { get; set; }
        public int CourseID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Course Course { get; set; }
        public virtual Course Course1 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
        public virtual FacultySection FacultySection { get; set; }
        public virtual FacultySection FacultySection1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAssignment> StudentAssignments { get; set; }
    }
}
