//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseFaculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseFaculty()
        {
            this.FacultySections = new HashSet<FacultySection>();
            this.FacultySections1 = new HashSet<FacultySection>();
        }
    
        public int CFID { get; set; }
        public int NumberOfSection { get; set; }
        public int CourseOfferedID { get; set; }
        public int EmpID { get; set; }
    
        public virtual CourseOffered CourseOffered { get; set; }
        public virtual CourseOffered CourseOffered1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacultySection> FacultySections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacultySection> FacultySections1 { get; set; }
    }
}
