//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultySection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacultySection()
        {
            this.Assignments = new HashSet<Assignment>();
            this.Assignments1 = new HashSet<Assignment>();
            this.CourseEnrollments = new HashSet<CourseEnrollment>();
            this.CourseEnrollments1 = new HashSet<CourseEnrollment>();
        }
    
        public int FSID { get; set; }
        public int CFID { get; set; }
        public int SectionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assignment> Assignments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseEnrollment> CourseEnrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseEnrollment> CourseEnrollments1 { get; set; }
        public virtual CourseFaculty CourseFaculty { get; set; }
        public virtual CourseFaculty CourseFaculty1 { get; set; }
        public virtual Section Section { get; set; }
        public virtual Section Section1 { get; set; }
        public virtual Section Section2 { get; set; }
    }
}
