//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FbID { get; set; }
        public System.DateTime Date { get; set; }
        public string FDescription { get; set; }
        public int Rating { get; set; }
        public int StudentID { get; set; }
    }
}
