//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public int ItemID { get; set; }
        public string ItemName { get; set; }
        public string ItemStatus { get; set; }
        public string IDescription { get; set; }
        public int Price { get; set; }
        public string filepath { get; set; }
    }
}
