//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fyp
    {
        public int FypID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectType { get; set; }
        public Nullable<int> CoSuperVisorID { get; set; }
        public string FypDescription { get; set; }
        public int SuperVisorEmpID { get; set; }
    }
}
