//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FypEvaluation
    {
        public int EvaluationID { get; set; }
        public Nullable<int> FypID { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<double> Criteria1Marks { get; set; }
        public Nullable<double> Criteria2Marks { get; set; }
        public Nullable<double> Criteria3Marks { get; set; }
        public Nullable<double> Criteria4Marks { get; set; }
        public Nullable<double> Criteria5Marks { get; set; }
        public string Deliverables1 { get; set; }
        public string Deliverables2 { get; set; }
        public string Deliverables3 { get; set; }
        public string Deliverables4 { get; set; }
        public string Deliverables5 { get; set; }
        public string ChangesRecommeneded { get; set; }
        public string DefenceStatus { get; set; }
        public Nullable<double> Deliverable1Completion { get; set; }
        public Nullable<double> Deliverable2Completion { get; set; }
        public Nullable<double> Deliverable3Completion { get; set; }
        public Nullable<double> Deliverable4Completion { get; set; }
        public Nullable<double> Deliverable5Completion { get; set; }
        public string Fyp2Deliverables { get; set; }
        public Nullable<int> ProjectProgress { get; set; }
        public Nullable<int> DocumentationStatus { get; set; }
        public string ProgressComments { get; set; }
    }
}
