//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FypMember
    {
        public int FypID { get; set; }
        public int LeaderID { get; set; }
        public Nullable<int> Member1ID { get; set; }
        public Nullable<int> Member2ID { get; set; }
    }
}
