//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FypProposal
    {
        public int ProposalID { get; set; }
        public string ProjectTitle { get; set; }
        public string ProjectType { get; set; }
        public string Abstract { get; set; }
        public int SupervisorID { get; set; }
        public Nullable<int> CoSupervisorID { get; set; }
        public string Comment { get; set; }
        public string Status { get; set; }
        public Nullable<int> LeaderID { get; set; }
        public Nullable<int> Member1ID { get; set; }
        public Nullable<int> Member2ID { get; set; }
    }
}
