//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOpening
    {
        public int JobID { get; set; }
        public int MinExperience { get; set; }
        public string JobDescription { get; set; }
        public System.DateTime DatePosted { get; set; }
        public Nullable<System.DateTime> ExpectedStartDate { get; set; }
        public int DesignationID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    }
}
