//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarksDistribution
    {
        public int MDID { get; set; }
        public int Title { get; set; }
        public double Weigtage { get; set; }
        public double TotalMarks { get; set; }
        public int FSID { get; set; }
    }
}
