//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penalty
    {
        public int NumberofDaysLate { get; set; }
        public int Rate { get; set; }
        public int PenaltyID { get; set; }
        public int IssueID { get; set; }
        public int ReturnID { get; set; }
    }
}
