//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PointPayment
    {
        public System.DateTime DepositDate { get; set; }
        public int NumberofDaysLate { get; set; }
        public int TotalPayable { get; set; }
        public int PaymentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> FeeID { get; set; }
    
        public virtual PointFee PointFee { get; set; }
        public virtual Student Student { get; set; }
    }
}
