//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSkill
    {
        public int PSID { get; set; }
        public string ApproveStatus { get; set; }
        public int ProjectID { get; set; }
        public int SkillID { get; set; }
    }
}
