//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectFramework
    {
        public int ID { get; set; }
        public string status { get; set; }
        public int projectID { get; set; }
        public int FID { get; set; }
    
        public virtual FrameworkLanguage FrameworkLanguage { get; set; }
        public virtual StudentProject StudentProject { get; set; }
    }
}
