//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestApproval
    {
        public string RequestStatus { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Remarks { get; set; }
        public int EmpID { get; set; }
        public string RequestID { get; set; }
    }
}
