//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class STransaction
    {
        public int TransactionID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public int Amount { get; set; }
        public int WalletID { get; set; }
        public int TypeID { get; set; }
    }
}
