//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAssignment
    {
        public int SubmissionID { get; set; }
        public double ObtainedMarks { get; set; }
        public double ObtainedWeightage { get; set; }
        public string AttachmentLink { get; set; }
        public System.DateTime SubmissionDateTime { get; set; }
        public int EnrollmentID { get; set; }
        public int AssignmentID { get; set; }
    
        public virtual Assignment Assignment { get; set; }
        public virtual CourseEnrollment CourseEnrollment { get; set; }
    }
}
