//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentOpening
    {
        public int SOpeningID { get; set; }
        public int SYear { get; set; }
        public int MaxSeats { get; set; }
        public System.DateTime LastApplicationDate { get; set; }
        public int ProgrammeID { get; set; }
    }
}
