//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPoint
    {
        public int StudentPointId { get; set; }
        public string PickUpAddress { get; set; }
        public Nullable<int> PointID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> SemesterID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual Point Point { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Student Student { get; set; }
    }
}
