//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PointDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Timetable
    {
        public int timetableID { get; set; }
        public Nullable<int> empID { get; set; }
        public Nullable<int> dayID { get; set; }
        public Nullable<int> courseID { get; set; }
        public Nullable<int> sectionID { get; set; }
        public Nullable<int> batchID { get; set; }
        public Nullable<int> roomID { get; set; }
        public Nullable<int> timeslotID { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Course Course { get; set; }
        public virtual daysofweek daysofweek { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Room Room { get; set; }
        public virtual Section Section { get; set; }
        public virtual Timeslot Timeslot { get; set; }
    }
}
